[theme]
base = "light"
primaryColor = "#F09000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F9"
textColor = "#003050"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
